routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});


Route::name('crags.')->group(function () {
    Route::get('/crags/create', 'CragsController@create')->name('create');
    Route::post('/crags/store', 'CragsController@store')->name('store');
    Route::get('/crags/{id}/climbs', 'CragsController@climbs')->name('climbs');
});


Route::name('climbs.')->group(function () {
    Route::get('/climbs/{id}', 'ClimbsController@show')->name('show');

    Route::get('/climbs/create/{id}', 'ClimbsController@create')->name('create');
    Route::post('/climbs/store', 'ClimbsController@store')->name('store');
    Route::post('/climbs/update', 'ClimbsController@update')->name('update');

        Route::get('/climbs/ajax/grades_styles', 'ClimbsController@ajaxGradesForStyles')->name('grades_styles.ajax');
        Route::get('/climbs/ajax/firstascent/autocomplete', 'ClimbsController@autoCompleteFirstAscent')->name('firstascent.autocomplete.ajax');

        Route::post('/climbs/ajax/update/description', 'ClimbsController@ajaxUpdateDescription')->name('description.update.ajax');
        Route::post('/climbs/ajax/update/weather_obs', 'ClimbsController@ajaxUpdateWeatherObs')->name('weather_obs.update.ajax');
        Route::post('/climbs/ajax/store/equipment', 'ClimbsController@ajaxStoreEquipment')->name('equipment.store.ajax');
        Route::post('/climbs/ajax/destroy/equipment', 'ClimbsController@ajaxDestroyEquipment')->name('equipment.destroy.ajax');
        Route::post('/climbs/ajax/store/firstascent', 'ClimbsController@ajaxStoreFirstAscent')->name('firstascent.store.ajax');
        Route::post('/climbs/ajax/destroy/firstascent', 'ClimbsController@ajaxDestroyFirstAscent')->name('firstascent.destroy.ajax');

});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Climbs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Climbs extends Model
{
    protected $table = 'g_climbs';

    protected $fillable = [
        'id_crag',
        'name',
        'id_style', 'id_grade', 'id_exposure'
    ];
//    protected $guarded = ['lat'];

    public $timestamps = false;


        public function style()
        {
            return $this->belongsTo('App\Styles', 'id_style', 'id');
        }

        public function grade()
        {
            return $this->belongsTo('App\Grades', 'id_grade', 'id');
        }

        public function exposure()
        {
            return $this->belongsTo('App\Exposure', 'id_exposure', 'id');
        }


        public function equipments()
        {
            return $this->belongsToMany(
                            'App\Equipments',
                            'App\ClimbsEquipments',
                            'id_climb',
                            'id_equipment')
                        ->withPivot('amount');
        }
#       return $this->hasManyThrough('App\Equipments', 'App\ClimbsEquipments', 'id_climb', 'id', 'id', 'id_equipment'); }

        public function firstascent()
        {
            return $this->belongsToMany('App\FirstAscent', 'App\ClimbsFirstAscent', 'id_climb', 'id_firstascent');
        }

}

app/Http/Controllers/ClimbsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Crags;
use App\Climbs;

use App\Equipments;
use App\Styles;
use App\Exposure;
use App\Grades;
use App\FirstAscent;

use App\StylesGrades;
use App\ClimbsEquipments;
use App\ClimbsFirstAscent;


class ClimbsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    
    public function show($id)
    {
        $climb = Climbs::where('id', $id)->first();

        $ndx_styles = Styles::orderby('title')->get();
        $ndx_exposure = Exposure::orderby('title')->get();

            $idStyle = $climb->id_style;
        $ndx_grades = Grades::whereHas('stylesGrades', function($q) use($idStyle) {
            $q->where('id_style', $idStyle);
        })->get();

        $ndx_equipments = Equipments::orderby('title')->get();

        $climb_firstascent = $this->getClimbFirstAscent($id);
        $climb_equipments = $this->getClimbEquipments($id);


/*            $climb_equipments = array();
            if(isset($climb->equipments) && !$climb->equipments->isEmpty()) {
                foreach($climb->equipments as $t) {
                    $climb_equipments[] = [ 'id'            => $t->id,
                                            'title'         => $t->title,
                                            'id_climb'      => $t->pivot->id_climb,
                                            'id_equipment'  => $t->pivot->id_equipment,
                                            'amount'        => $t->pivot->amount,]; }
            }                           */

        return view('pages.climbs.climb', compact(
                                            'climb',
                                            'ndx_equipments',
                                            'ndx_styles',
                                            'ndx_exposure',
                                            'ndx_grades'))
                    ->with(['climb_equipments' => $climb_equipments,
                            'climb_firstascent' => $climb_firstascent]);
    }


    public function create($id)
    {
        return view('pages.climbs.create', compact('crags', 'id'));
    }


    public function store(Request $request)
    {
            $action = Climbs::firstOrCreate(
                            $request->only('name', 'id_crag'),
                            [$request->only('id_style', 'id_grade', 'id_exposure'), 'id_user' => Auth::id()]
                        );

        return redirect()->route('home');
    }


    function update(Request $request)
    {
        $action = Climbs::findOrFail($request->id);

            $action->name           = $request->name;
            $action->id_style       = $request->id_style;
            $action->id_grade       = $request->id_grade;
            $action->id_exposure    = $request->id_exposure;

        $action->save();

            if($action->wasChanged()) {
                $climb = Climbs::where('id', $action->id)->first();
                    $s['name'] = $climb->name;

                    $s['style'] = (isset($climb->style) ? $climb->style->title : '--');
                    $s['grade'] = (isset($climb->grade) ? $climb->grade->title : '--');
                    $s['exposure'] = (isset($climb->exposure) ? $climb->exposure->title : '--');

            return response()->json($s);
            }
    }

/* ----- ----- ----- ----- ----- ----- ----- -----
   ----- ----- ----- ----- ----- ----- ----- -----  */


    public function ajaxGradesForStyles(Request $request)
    {
/*        $styles_grades = StylesGrades::where('id_style', $request->id)->get();

            $s = array();

            if(!$styles_grades->isEmpty()) {
                foreach($styles_grades as $t)
                    $s[] = $t->grades;
            }   */
            $idStyle = $request->id;
            $ndx_grades = Grades::whereHas('stylesGrades', function($q) use($idStyle) {
                $q->where('id_style', $idStyle);
            })->get();
        return response()->json($ndx_grades);
    }


    public function ajaxUpdateDescription(Request $request)
    {
        $action = Climbs::findOrFail($request->id_climb);

            $action->description = $request->description;
        
        $action->save();

            if($action->wasChanged()) {
        
                return response()->json(['description' => $action->description]);
            }
    }


    public function ajaxUpdateWeatherObs(Request $request)
    {
        $action = Climbs::findOrFail($request->id_climb);

            $action->weather = $request->weather;
            $action->obs = $request->obs;
        
        $action->save();

            if($action->wasChanged()) {
        
                return response()->json(['weather' => $action->weather, 'obs' => $action->obs,]);
            }
    }


    public function ajaxStoreEquipment(Request $request)
    {
        $action = ClimbsEquipments::firstOrCreate(
                        $request->only('id_climb', 'id_equipment'),
                        $request->only('amount'));


        if($action->wasRecentlyCreated) {
            $equipments = $this->getClimbEquipments($request->id_climb);

        return response()->json($equipments);
        }
    }


    public function ajaxDestroyEquipment(Request $request)
    {
        $action = ClimbsEquipments::where('id_climb', $request->id_climb)
                                    ->where('id_equipment', $request->id_equipment)
                                    ->delete();

            if($action == true) {
                $equipments = $this->getClimbEquipments($request->id_climb);

            return response()->json($equipments); }
    }


    public function ajaxStoreFirstAscent(Request $request)
    {
        $action = FirstAscent::firstOrCreate(
                        $request->only('name'));

        if(!empty($action->id)) {

            $idFirstAscent = $action->id;
            unset($action);

                $action = ClimbsFirstAscent::firstOrCreate(
                            [   'id_climb' => $request->id_climb,
                                'id_firstascent' => $idFirstAscent]);
        }

        if($action->wasRecentlyCreated) {

            $firstascent = $this->getClimbFirstAscent($request->id_climb);
/*        $idClimb = $request->id_climb;

            $firstascent = FirstAscent::whereHas('climbsFirstAscent', function($q) use($idClimb) {
                $q->where('id_climb', $idClimb);
            })->get();  */

        return response()->json($firstascent); }
    }

    public function ajaxDestroyFirstAscent(Request $request)
    {
        $action = ClimbsFirstAscent::where('id_climb', $request->id_climb)
                                    ->where('id_firstascent', $request->id_firstascent)
                                    ->delete();

            if($action == true) {
                $firstascent = $this->getClimbFirstAscent($request->id_climb);

            return response()->json($firstascent); }
    }


/* ----- ----- ----- ----- ----- ----- ----- -----
   ----- ----- ----- ----- ----- ----- ----- -----  */


        private function getClimbEquipments($id_climb)
        {
            $climb_equipments = ClimbsEquipments::where('id_climb', $id_climb)->get();

                foreach($climb_equipments as $t)
                $equipments[] = [   'id'            => $t->equipments->id,
                                    'id_climb'      => $t->id_climb,
                                    'id_equipment'  => $t->id_equipment,
                                    'title'         => $t->equipments->title,
                                    'amount'        => $t->amount, ];

            return $equipments;
        }


        private function getClimbFirstAscent($id_climb)
        {
            $firstascent = [];

            $climb_firstascent = ClimbsFirstAscent::where('id_climb', $id_climb)->get();

                foreach($climb_firstascent as $t)
                $firstascent[] = [  'id'            => $t->firstascent->id,
                                    'id_climb'      => $t->id_climb,
                                    'id_firstascent'=> $t->id_firstascent,
                                    'name'         => $t->firstascent->name, ];

            return $firstascent;
        }


        public function autoCompleteFirstAscent(Request $request)
        {
            $data = FirstAscent::select("name")
                        ->where("name","LIKE","%{$request->input('query')}%")
                        ->limit('15')
                        ->get();

            return response()->json($data);
        }


}

resources/views/pages/climbs/includes/equipments.blade.php
        <div class="col-xl-4">

<!-- BEGIN: Card Equipamentos -->
        <div id="card_equipments" class="card">

            <div class="card-header border-0">
                <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0">{{ __('Equipamentos') }}</h3>
                </div>

                <div class="col text-right">
                    <button id="btn_form_equipment" class="btn btn-sm btn-info rounded-circle text-white p-1 px-2 ml-3"
                        data-toggle="tooltip" data-placement="right" title="{{ __('Adicionar') }}">
                        <i class="ni ni-fat-add"></i>
                    </button>
                </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="table_equipments" class="table align-items-center table-flush">

                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Qut.</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>

                    <tbody>
                    </tbody>

                </table>
            </div>

        </div>
<!-- END: Card Equipamentos -->


<!-- BEGIN: Form Equipamentos -->
            <div id="card_form_equipment" class="card d-none">
                <div class="card-header">
                    <h3 class="mb-0">{{ __('Adicionar Equipamento') }}</h3>
                </div>

                <div class="card-body">

                    {{ Form::open(array('id' => 'form_add_equipment', 'route' => 'climbs.equipment.store.ajax', 'method' => 'post')) }}

                    {{ Form::hidden('id_climb', $climb->id, array('id' => 'id_climb', 'class' => 'form-control')) }}

                    <div class="form-row mb-3">
                        <div class="col">
                            {{ Form::label('id_equipment', __('Equipamento'), array('class' => 'small font-weight-bold')) }}
                            {{ Form::select('id_equipment', $ndx_equipments->pluck('title', 'id'), null, array('id' => 'id_equipment', 'class' => 'form-control', 'placeholder' => 'Selecione')) }}
                        </div>

                        <div class="col">
                            {{ Form::label('amount', __('Quantidade'), array('class' => 'small font-weight-bold')) }}
                            {{ Form::text('amount', null, array('id' => 'amount', 'class' => 'form-control', 'placeholder' => 'Quantidade')) }}
                        </div>
                    </div>

                        {{ Form::submit(__('Salvar'), array('id' => 'btn_save_equipment', 'class' => 'btn btn-small btn-primary')) }}
                        {{ Form::button(__('Cancelar'), array('id' => 'btn_cancel_form_equipment', 'class' => 'btn btn-small btn-danger')) }}

                        {{ Form::close() }}

                </div>
            </div>
<!-- END: Form Equipamentos -->

        </div>


@push('js-include')
<script>
/* ----- ----- ----- ----- ----- ----- ----- -----
   --- JS: Equipments
   ----- ----- ----- ----- ----- ----- ----- -----  */

// --- BTN: Controles para Data/Form dos EQUIPAMENTOS
    $('#btn_form_equipment, #btn_cancel_form_equipment').on('click',function(){
        resetFormEquipments();
        $('#card_equipments, #card_form_equipment').toggleClass('d-none');
    });


// --- FORM: criar registro de equipamento vinculado
    $( "#form_add_equipment" ).submit(function( event ) {
    event.preventDefault();

    var id_climb = $('#id_climb').val();
    var id_equipment = $('#id_equipment').val();
    var amount = $('#amount').val();

        $.ajax({
            type        : 'POST',
            url         : '{{ route("climbs.equipment.store.ajax") }}',
            dataType    : "JSON",
                data    : {
                    "_token": "{{ csrf_token() }}",
                    id_climb: id_climb,
                    id_equipment: id_equipment,
                    amount: amount,
                },
                    success: function(data){
                        var alert = '<strong>Info!</strong> Registro Ok!';

                        showEquipments(data);
                        callAlerts(alert, 'primary');

                            resetFormEquipments();
                            $('#card_equipments, #card_form_equipment').toggleClass('d-none');
                    }
        });

    return false;
    });


// --- BTN-ACTION: excluir registro de equipamento vinculado
    $('#table_equipments tbody').on('click','.btn-danger',function(){

    var id = $(this).data('id').split('_');

        $.ajax({
            type        : 'POST',
            url         : '{{ route("climbs.equipment.destroy.ajax") }}',
            dataType    : "JSON",
            data    : {
                    "_token": "{{ csrf_token() }}",
                    id_climb: id[0],
                    id_equipment: id[1],
                },
                    success: function(data){
                        var alert = '<strong>Info:</strong> registro removido!';

                        showEquipments(data);
                        callAlerts(alert, 'primary');

                            resetFormEquipments();
                    }
        });

    return false;
    });

// --- Reset dos campos do formulário de equipamentos
        function resetFormEquipments() {
            $('#form_add_equipment select[name="id_equipment"]').val("");
            $('#form_add_equipment input[name="amount"]').val("");
        }

// --- Alimenta layout de equipamentos
        function showEquipments(data) {

        var html = '';
        var i;

            for(i=0; i<data.length; i++)
            {
            html += '<tr>' +
                        '<th scope="row">' + data[i].amount + '</th>' +
                        '<td>' + data[i].title + '</td>' +
                        '<td>' +
                        '<button class="btn btn-sm btn-danger align-top rounded-circle text-white p-1 px-2 ml-3" ' +
                            'data-id="' + data[i].id_climb + '_' + data[i].id_equipment + '"' +
                            'data-toggle="tooltip" data-placement="right" title="{{ __('Remover') }}">' +
                            '<i class="ni ni-fat-remove"></i>' +
                        '</button>' +
                        '</td>' +
                    '</tr>';
            }

            $('#table_equipments tbody').html(html);
        }
</script>
@endpush

resources/views/pages/climbs/includes/firstascent.blade.php
    <div class="col-xl-8">

<!-- BEGIN: Card Conquistadores -->
        <div id="card_firstascent" class="card">

            <div class="card-header border-0">
                <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0">{{ __('Conquistadores') }}</h3>
                </div>

                <div class="col text-right">
                    <button id="btn_form_firstascent" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="right" title="{{ __('Adicionar') }}">
                        <i class="ni ni-fat-add"></i>
                    </button>
                </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="table_firstascent" class="table align-items-center table-flush">

                    <thead class="thead-light">
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                    </thead>

                    <tbody>
                    </tbody>

                </table>
            </div>
        </div>
<!-- END: Card Conquistadores -->


<!-- BEGIN: Form Conquistadores -->
        <div id="card_form_firstascent" class="card d-none">
            <div class="card-header">
                <h3 class="mb-0">{{ __('Adicionar Conquistador') }}</h3>
            </div>

            <div class="card-body">

                {{ Form::open(array('id' => 'form_add_firstascent', 'route' => 'climbs.firstascent.store.ajax', 'method' => 'post')) }}

                {{ Form::hidden('id_climb', $climb->id, array('id' => 'id_climb', 'class' => 'form-control')) }}

                    <div class="form-row mb-3">
                        <div class="col">
                            {{ Form::label('firstascent', __('Conquistador'), array('class' => 'small font-weight-bold')) }}
                            {{ Form::text('firstascent', null, array('id' => 'firstascent', 'class' => 'form-control', 'placeholder' => 'Selecione')) }}
                        </div>
                    </div>

                    {{ Form::submit(__('Salvar'), array('id' => 'btn_save_firstascent', 'class' => 'btn btn-small btn-primary')) }}
                    {{ Form::button(__('Cancelar'), array('id' => 'btn_cancel_form_firstascent', 'class' => 'btn btn-small btn-danger')) }}

                {{ Form::close() }}
            </div>
        </div>
<!-- END: Form Conquistadores -->

    </div>


@push('js-include')
<script>
/* ----- ----- ----- ----- ----- ----- ----- -----
   --- JS: FirstAscent
   ----- ----- ----- ----- ----- ----- ----- -----  */

// --- BTN: Controles para Data/Form dos CONQUISTADORES
 $('#btn_form_firstascent, #btn_cancel_form_firstascent').on('click',function(){
  resetFormFirstAscent();
  $('#card_firstascent, #card_form_firstascent').toggleClass('d-none');
 });

// --- INPUT: autocomplete para campo de Conquistadores
    $('#form_add_firstascent #firstascent').typeahead({
        source: function (query, process) {
            return $.get("{{ route('climbs.firstascent.autocomplete.ajax') }}", { query: query }, function (data) {
                return process(data);
            });
        }
    });

// --- FORM: criar registro de conquistador
    $( "#form_add_firstascent" ).submit(function( event ) {
    event.preventDefault();

    var id_climb = $(this['id_climb']).val();
    var name = $(this['firstascent']).val();

        $.ajax({
            type        : 'POST',
            url         : '{{ route("climbs.firstascent.store.ajax") }}',
            dataType    : "JSON",
                data    : {
                    "_token": "{{ csrf_token() }}",
                    id_climb: id_climb,
                    name: name,
                },
                    success: function(data){
                        var alert = '<strong>Info!</strong> Registro Ok!';

                            showFirstAscent(data);
                            callAlerts(alert, 'primary');

                            resetFormFirstAscent();
                            $('#card_firstascent, #card_form_firstascent').toggleClass('d-none');
                    }
        });
    return false;
    });

// --- BTN-ACTION: excluir registro de conquistador
    $('#table_firstascent tbody').on('click','.btn-danger',function(){

    var id = $(this).data('id').split('_');

        $.ajax({
            type        : 'POST',
            url         : '{{ route("climbs.firstascent.destroy.ajax") }}',
            dataType    : "JSON",
            data    : {
                    "_token": "{{ csrf_token() }}",
                    id_climb: id[0],
                    id_firstascent: id[1],
                },
                    success: function(data){
                        var alert = '<strong>Info:</strong> registro removido!';
                        showFirstAscent(data);
                        callAlerts(alert, 'primary');
                            resetFormFirstAscent();
                    }
        });
    return false;
    });

// --- Reset dos campos do formulário de conquistadores
        function resetFormFirstAscent() {
            $('#form_add_firstascent input[name="firstascent"]').val("");
        }

// --- Alimenta layout de conquistadores
        function showFirstAscent(data) {
        var html = '';
        var i;

            for(i=0; i<data.length; i++)
            {
            html += '<tr>' +
                        '<th scope="row">' + data[i].name + '</th>' +
                        '<td class="text-right">' +
                        '<button class="btn btn-sm btn-danger align-top rounded-circle text-white p-1 px-2 ml-3" ' +
                            'data-id="' + data[i].id_climb + '_' + data[i].id_firstascent + '"' +
                            'data-toggle="tooltip" data-placement="right" title="{{ __('Remover') }}">' +
                            '<i class="ni ni-fat-remove"></i>' +
                        '</button>' +
                        '</td>' +
                    '</tr>';
            }

            $('#table_firstascent tbody').html(html);
        }
</script>
@endpush

resources/views/pages/climbs/includes/info.blade.php
<!-- BEGIN: Header Info -->
    <div id="row_info" class="row mb-4">
    <div class="col-12">

        <!-- Title-Blocos -->
        <div class="card bg-primary mr-4 d-inline-block">
        <div id="row_info_name" class="card-body px-4 pt-1 pb-2 h1 m-0 text-white">
            {{ $climb->name }}
        </div>
        </div>

        <div class="card bg-default mr-4 d-inline-block">
        <div class="card-body px-4 pt-1 pb-2 h1 m-0 text-white">
            <span id="row_info_style">
                {{ isset($climb->style) ? $climb->style->title : '--' }}
            </span>
        </div>
        </div>

        <div class="card bg-warning d-inline-block">
        <div class="card-body px-4 pt-1 pb-2 h1 m-0 text-white">
            <span id="row_info_grade">
                {{ isset($climb->grade) ? $climb->grade->title : '--' }}
            </span>

                    /

            <span id="row_info_exposure">
                {{ isset($climb->exposure) ? $climb->exposure->title : '--' }}
            </span>
        </div>
        </div>

        <!-- Button Add -->
        <button id="btn_form_info" class="btn btn-primary align-top rounded-circle text-white p-1 px-2 ml-3"
            data-toggle="tooltip" data-placement="right" title="{{ __('Editar') }}">
            <i class="ni ni-ruler-pencil"></i>
        </button>

    </div>
    </div>
<!--END: Header Info -->


<!-- BEGIN: Formulário Editar Info da Via -->
    <div id="row_edit_info" class="row mb-5 d-none">
    <div class="col-12">

        {{ Form::open(array('id' => 'form_edit_climb', 'route' => 'climbs.update', 'method' => 'post', 'class' => 'bg-form rounded p-3')) }}

            {{ Form::hidden('id_climb', $climb->id, array('class' => 'form-control')) }}

            <div class="form-row mb-3">
                {{ Form::text('name', $climb->name, array('class' => 'form-control')) }}
            </div>

            <div class="form-row mb-3">
                <div class="col">
                {{ Form::select('id_style', $ndx_styles->pluck('title', 'id'), $climb->id_style, array('id' => 'id_style', 'class' => 'form-control', 'placeholder' => __('Selecione'))) }}
                </div>

                <div class="col">
                {{ Form::select('id_grade', $ndx_grades->pluck('title', 'id'), $climb->id_grade, array('id' => 'id_grade', 'class' => 'form-control', 'placeholder' => __('Selecione'))) }}
                </div>

                <div class="col">
                {{ Form::select('id_exposure', $ndx_exposure->pluck('title', 'id'), $climb->id_exposure, array('id' => 'id_exposure', 'class' => 'form-control', 'placeholder' => __('Selecione'))) }}
                </div>
            </div>

            {{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
            {{ Form::button('Cancelar', array('id' => 'btn_cancel_form_info', 'class' => 'btn btn-sm btn-danger btn_form_cancel')) }}

        {{ Form::close() }}
    </div>
    </div>
<!-- END: Formulário Registrar Via -->

@push('js-include')
<script>
/* ----- ----- ----- ----- ----- ----- ----- -----
   --- JS: Info (header)
   ----- ----- ----- ----- ----- ----- ----- -----  */

// --- BTN: Controles para Data/Form das INFORMAÇÕES (no header do container)
$('#btn_form_info, #btn_cancel_form_info').on('click',function(){
        $('#row_edit_info').toggleClass('d-none');
    });

// --- FORM: atualiza informações da via
    $("#form_edit_climb").submit(function( event ) {
    event.preventDefault();

    var id_climb = $(this['id_climb']).val();
    var name = $(this['name']).val();
    var id_style = $(this['id_style']).val();
    var id_grade = $(this['id_grade']).val();
    var id_exposure = $(this['id_exposure']).val();

        $.ajax({
            type        : 'POST',
            url         : '{{ route("climbs.update") }}',
            dataType    : "JSON",
                data    : {
                    "_token": "{{ csrf_token() }}",
                    id:             id_climb,
                    name:           name,
                    id_style:       id_style,
                    id_grade:       id_grade,
                    id_exposure:    id_exposure,
                },
                    success: function(data){
                        var alert = '<strong>Info!</strong> Registro Ok!';

                        $('#row_info_name').html(data.name);
                        $('#row_info_style').html(data.style);
                        $('#row_info_grade').html(data.grade);
                        $('#row_info_exposure').html(data.exposure);

                            $('#row_edit_info').addClass('d-none');
                    }
        });

    return false;
    });

// --- FORM-CONTROL: Alimenta select de Graduação (id_grade) a partir da posição do select de Estilo (id_style)
    $('#form_edit_climb #id_style').on('change',function(){

    var idStyle = $(this).val();

        $.ajax({
            type        : 'GET',
            url         : '{{ route("climbs.grades_styles.ajax") }}',
            async       : false,
            dataType    : "JSON",
                data    : {
                    id: idStyle,
                },
                    success: function(data){
                        var html = '';
                        var i;

                        for(i=0; i<data.length; i++)
                        {
                            html += '<option value="' + data[i].id +'">' + data[i].title + '</option>';
                        }

                            html += '<option value="">{{ __('sem graduação') }}</option>';

                        $('#form_edit_climb #id_grade').html(html);
                    }
        });

            if(idStyle == 1) {
                $("#form_edit_climb #id_exposure").attr('disabled',true).val('');
            }

            else {
                $("#form_edit_climb #id_exposure").attr('disabled',false);
            }
    });
</script>
@endpush